# Complete installation of probe and addons
# Test packages installation, conf file, informations existence and script output


###############
## VARIABLES ##
###############

set timeout 1

# List of expected addons
set addons_list "filesystem file log snmp odbc"

# Install script path
set install_script "install.sh"


###########
## TESTS ##
###########

## Script running
#set process_id [spawn su root -c "sh $install_script"]
#expect -re ": $"
#send "root\n";

set process_id [spawn sh $install_script]

# Password invite
test_expect "install_password_invite" "To download ECHOES Alert Probe, you have to enter your password\..\n*Note: login is .*\nPassword: $"

# send password
send "147258369aA\n"

# Update asset
test_expect "install_put-asset_wait" "#+ 100,0%"
test_expect "install_put-asset_http-code" "HTTP_CODE: 200"

# Download probe
test_expect "install_probe_wait" "#+ 100,0%"
test_expect "install_probe_http-code" "HTTP_CODE: 200"
test_expect "install_probe_message-downloaded" "ECHOES Alert Probe downloaded."

# Download and install common lib
test_expect "install_common_wait" "#+ 100,0%"
test_expect "install_common_http-code" "HTTP_CODE: 200"
test_expect "install_common_message-downloaded" "ECHOES Alert add-on common library downloaded."
set timeout 30
test_expect "install_common_message-installed" "ECHOES Alert add-on common library installed."
set timeout 1
test_package_installed "install_common_installed" "ea-probe-addon"

# Install and configure probe
set timeout 30
test_expect "install_probe_message-installed" "ECHOES Alert Probe installed."
set timeout 1
test_package_installed "install_probe_installed" "ea-probe"
test_expect "install_probe_message-configured" "ECHOES Alert Probe configured."
test_string_equal "install_conf_token" [get_value_in_file "TOKEN" $install_script] [get_value_in_file "token" "[get_value_in_file "INSTALL_DIR" $install_script]/etc/probe.conf"]
test_is_digit "install_conf_probe-id_integer" [get_value_in_file "probe_id" "[get_value_in_file "INSTALL_DIR" $install_script]/etc/probe.conf"]
test_is_greater "install_conf_probe-id_greater-than-zero" [get_value_in_file "probe_id" "[get_value_in_file "INSTALL_DIR" $install_script]/etc/probe.conf"] 0

# Download and install addons
test_expect "install_addons-list_wait" "#+ 100,0%"
test_expect "install_addons-list_http-code" "HTTP_CODE: 200"
foreach addon $addons_list {
	test_expect "install_addon${addon}_wait" "#+ 100,0%"
	test_expect "install_addon${addon}_http-code" "HTTP_CODE: 200"
	test_expect "install_addon${addon}_message-downloaded" "ECHOES Alert add-on ${addon} library downloaded."
	set timeout 30
	test_expect "install_addon${addon}_message-installed" "ECHOES Alert add-on ${addon} library installed."
	set timeout 1
	test_package_installed "install_addon${addon}_installed" "ea-probe-addon${addon}"
}

# Download and copy informations
test_expect "install_informations_wait" "#+ 100,0%"
test_expect "install_informations_http-code" "HTTP_CODE: 200"
test_expect "install_informations_message-downloaded" "ECHOES Alert informations downloaded."
test_file_exist "install_informations_exist" "/opt/echoes-alert/probe/etc/informations.json"

# Start daemon and finish install script
test_expect "install_daemon_start_message" " \* Starting ECHOES Alert Probe  ea-probe.*\n$"
test_return_code "install_return_code" $process_id 0

# Tests if ea-probe service is running
test_is_service_running "install_daemon_alive" "ea-probe"


###########
## AFTER ##
###########

# Stop probe 
set spawn_pid [spawn service ea-probe stop]
wait_spawn_end $spawn_pid
